export const WORKLOG_REQUEST = 'WORKLOG_REQUEST';
export const WORKLOG_REQUEST_SUCCESS = 'WORKLOG_REQUEST_SUCCESS';
export const WORKLOG_REQUEST_FAILED = 'WORKLOG_REQUEST_FAILED';

export const ASSIGNED_ISSUES_REQUEST = 'ASSIGNED_ISSUES_REQUEST';
export const ASSIGNED_ISSUES_REQUEST_SUCCESS = 'ASSIGNED_ISSUES_REQUEST_SUCCESS';
export const ASSIGNED_ISSUES_REQUEST_FAILED = 'ASSIGNED_ISSUES_REQUEST_FAILED';

export const ADD_WORKLOG_REQUEST = 'ADD_WORKLOG_REQUEST';
export const ADD_WORKLOG_REQUEST_SUCCESS = 'ADD_WORKLOG_REQUEST_SUCCESS';
export const ADD_WORKLOG_REQUEST_FAILED = 'ADD_WORKLOG_REQUEST_FAILED';